from setuptools import setup

setup(
    name='Testing',
    version='0.01',
    packages=['PyEnv1.Lib.site-packages.pip', 'PyEnv1.Lib.site-packages.pip._vendor',
              'PyEnv1.Lib.site-packages.pip._vendor.idna', 'PyEnv1.Lib.site-packages.pip._vendor.pep517',
              'PyEnv1.Lib.site-packages.pip._vendor.pytoml', 'PyEnv1.Lib.site-packages.pip._vendor.certifi',
              'PyEnv1.Lib.site-packages.pip._vendor.chardet', 'PyEnv1.Lib.site-packages.pip._vendor.chardet.cli',
              'PyEnv1.Lib.site-packages.pip._vendor.distlib', 'PyEnv1.Lib.site-packages.pip._vendor.distlib._backport',
              'PyEnv1.Lib.site-packages.pip._vendor.msgpack', 'PyEnv1.Lib.site-packages.pip._vendor.urllib3',
              'PyEnv1.Lib.site-packages.pip._vendor.urllib3.util',
              'PyEnv1.Lib.site-packages.pip._vendor.urllib3.contrib',
              'PyEnv1.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'PyEnv1.Lib.site-packages.pip._vendor.urllib3.packages',
              'PyEnv1.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'PyEnv1.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'PyEnv1.Lib.site-packages.pip._vendor.colorama', 'PyEnv1.Lib.site-packages.pip._vendor.html5lib',
              'PyEnv1.Lib.site-packages.pip._vendor.html5lib._trie',
              'PyEnv1.Lib.site-packages.pip._vendor.html5lib.filters',
              'PyEnv1.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'PyEnv1.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'PyEnv1.Lib.site-packages.pip._vendor.html5lib.treebuilders',
              'PyEnv1.Lib.site-packages.pip._vendor.lockfile', 'PyEnv1.Lib.site-packages.pip._vendor.progress',
              'PyEnv1.Lib.site-packages.pip._vendor.requests', 'PyEnv1.Lib.site-packages.pip._vendor.packaging',
              'PyEnv1.Lib.site-packages.pip._vendor.cachecontrol',
              'PyEnv1.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'PyEnv1.Lib.site-packages.pip._vendor.webencodings', 'PyEnv1.Lib.site-packages.pip._vendor.pkg_resources',
              'PyEnv1.Lib.site-packages.pip._internal', 'PyEnv1.Lib.site-packages.pip._internal.cli',
              'PyEnv1.Lib.site-packages.pip._internal.req', 'PyEnv1.Lib.site-packages.pip._internal.vcs',
              'PyEnv1.Lib.site-packages.pip._internal.utils', 'PyEnv1.Lib.site-packages.pip._internal.models',
              'PyEnv1.Lib.site-packages.pip._internal.commands', 'PyEnv1.Lib.site-packages.pip._internal.operations',
              'djangoTest.apiTest', 'djangoTest.apiTest.migrations', 'djangoTest.djangoTest'],
    url='https://github.com/OmarCantuariasSaleh/Testing',
    license='',
    author='Admin',
    author_email='omarcantuarias@hotmail.com',
    description='prueba de django'
)
